const entities = {
  auth: {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    REGENERATE_PASSWORD: 'REGENERATE_PASSWORD',
    CHANGE_PASSWORD: 'CHANGE_PASSWORD',
    ADMIN_LOGIN: 'ADMIN_LOGIN',
    RESEND_OTP: 'RESEND_OTP'
  },
  account: {
    GENERATE_ACCOUNT_OTP: 'GENERATE_ACCOUNT_OTP',
    VALIDATE_ACCOUNT_OTP: 'VALIDATE_ACCOUNT_OTP',
    GET_ACCOUNT_DETAILS: 'GET_ACCOUNT_DETAILS',
    VERIFY_EMAIL_ADDRESS: 'VERIFY_EMAIL_ADDRESS',
    GET_PERSONAL_INFORMATION: 'GET_PERSONAL_INFORMATION',
    SAVE_PERSONAL_INFORMATION: 'SAVE_PERSONAL_INFORMATION',
    SAVE_BUSINESS_INFORMATION: 'SAVE_BUSINESS_INFORMATION',
    GET_BUSINESS_INFORMATION: 'GET_BUSINESS_INFORMATION',
    GET_STATES: 'GET_STATES',
    GET_LGAS_BY_STATE: 'GET_LGAS_BY_STATE',
    GET_REGIONS_BY_STATE: 'GET_REGIONS_BY_STATE',
    SAVE_REGION_INFORMATION: 'SAVE_REGION_INFORMATION',
    GET_REGION_INFORMATION: 'GET_REGION_INFORMATION',
    GET_ACCOUNT_SUMMARY: 'GET_ACCOUNT_SUMMARY',
    SAVE_ACCOUNT_SUMMARY: 'SAVE_ACCOUNT_SUMMARY',
    GET_ZAC_INFORMATION: 'GET_ZAC_INFORMATION',
  },

  dashboard: {
    superAdmin: {
      GET_SUPER_ADMIN_DASHBOARD_DATA: 'GET_SUPER_ADMIN_DASHBOARD_DATA',
      GET_ZAC_INFO_BY_STATE: 'GET_ZAC_INFO_BY_STATE',
      SAVE_ONBOARD_ADMIN_USER: 'SAVE_ONBOARD_ADMIN_USER',
    },
    zonalCordinator: {
      GET_ZAC_DASHBOARD_DATA: 'GET_ZAC_DASHBOARD_DATA',
    },
    general: {
      GET_OTHER_USERS_DASHBOARD_INFO: 'GET_OTHER_USERS_DASHBOARD_INFO',
    },
  },
  xFrame: {
    SET_XFRAME_OPTIONS: 'SET_XFRAME_OPTIONS',
  },
};

export default entities;
