apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentgateway #The name of the Kubernetes Deployment to be created in the Kubernetes cluster
  labels:
    app: paymentgateway
spec:
  replicas: 2 #The number of pods to be created in the Kubernetes cluster for the React.js application container
  selector:
    matchLabels:
      app: paymentgateway
  template:
    metadata:
      labels:
        app: paymentgateway 
    spec:
      containers:
      - name: paymentgateway #The name of the react.js application container
        image: 986798253017.dkr.ecr.us-east-1.amazonaws.com/devops_practice:latest #The Docker image for building the React.js application container
        ports:
        - containerPort: 3000 #The port for the React.js application   container
