version: 2.1
executors:
  docker-executor:
    docker:
      - image: circleci/node:12.22.7

jobs:
  build:
    executor: docker-executor

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Build
          command: npm run build

      - run:
          name: Build Docker image
          command: |
            docker build -t your-dockerhub-username/your-image-name:${CIRCLE_SHA1} .
            docker login -u your-dockerhub-username -p your-dockerhub-password
            docker push your-dockerhub-username/your-image-name:${CIRCLE_SHA1}

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
